debug: true

global:
  apikey: &apikey "AABBCCDDEEFFGG"
  storageClassName: &storageClassName "nfs"
  ingressClassName: &ingressClassName "traefik"
  certManagerClusterIssuer: &issuer "selfsigned-cluster-issuer"
  authMethod: External

metrics:
  enabled: &metricsEnabled false

initJellyseerr: true
notifications:
  telegram:
    enabled: false
    chat_id: ""
    bot_apitoken: ""

dash:
  username: admin
  password: str0ngP4ssw0rd
  mail: admin@gmail.com
  countryCode: "US"
  preferredLanguage: "en"

torrent:
  username: ci-admin
  password: str0ngP455

indexers:
  - name: 1337x
    body:
      added: "0001-01-01T00:00:00Z"
      appProfileId: 1
      capabilities:
        bookSearchParams:
          - q
        categories:
          - id: 5000
            name: TV
            subCategories:
              - id: 5070
                name: TV/Anime
                subCategories: []
              - id: 5040
                name: TV/HD
                subCategories: []
              - id: 5030
                name: TV/SD
                subCategories: []
              - id: 5080
                name: TV/Documentary
                subCategories: []
          - id: 3000
            name: Audio
            subCategories:
              - id: 3010
                name: Audio/MP3
                subCategories: []
              - id: 3040
                name: Audio/Lossless
                subCategories: []
              - id: 3020
                name: Audio/Video
                subCategories: []
              - id: 3050
                name: Audio/Other
                subCategories: []
              - id: 3030
                name: Audio/Audiobook
                subCategories: []
          - id: 2000
            name: Movies
            subCategories:
              - id: 2070
                name: Movies/DVD
                subCategories: []
              - id: 2030
                name: Movies/SD
                subCategories: []
              - id: 2010
                name: Movies/Foreign
                subCategories: []
              - id: 2040
                name: Movies/HD
                subCategories: []
              - id: 2060
                name: Movies/3D
                subCategories: []
              - id: 2045
                name: Movies/UHD
                subCategories: []
          - id: 4000
            name: PC
            subCategories:
              - id: 4030
                name: PC/Mac
                subCategories: []
              - id: 4070
                name: PC/Mobile-Android
                subCategories: []
              - id: 4060
                name: PC/Mobile-iOS
                subCategories: []
              - id: 4050
                name: PC/Games
                subCategories: []
              - id: 4040
                name: PC/Mobile-Other
                subCategories: []
          - id: 1000
            name: Console
            subCategories:
              - id: 1080
                name: Console/PS3
                subCategories: []
              - id: 1020
                name: Console/PSP
                subCategories: []
              - id: 1040
                name: Console/XBox
                subCategories: []
              - id: 1050
                name: Console/XBox 360
                subCategories: []
              - id: 1090
                name: Console/Other
                subCategories: []
              - id: 1030
                name: Console/Wii
                subCategories: []
              - id: 1010
                name: Console/NDS
                subCategories: []
              - id: 1110
                name: Console/3DS
                subCategories: []
              - id: 1180
                name: Console/PS4
                subCategories: []
          - id: 6000
            name: XXX
            subCategories:
              - id: 6010
                name: XXX/DVD
                subCategories: []
              - id: 6060
                name: XXX/ImageSet
                subCategories: []
          - id: 8000
            name: Other
            subCategories:
              - id: 8010
                name: Other/Misc
                subCategories: []
          - id: 7000
            name: Books
            subCategories:
              - id: 7020
                name: Books/EBook
                subCategories: []
              - id: 7030
                name: Books/Comics
                subCategories: []
        limitsDefault: 100
        limitsMax: 100
        movieSearchParams:
          - q
        musicSearchParams:
          - q
          - album
          - artist
        searchParams:
          - q
          - q
        supportsRawSearch: true
        tvSearchParams:
          - q
          - season
          - ep
      configContract: CardigannSettings
      definitionName: 1337x
      description: 1337X is a Public torrent site that offers verified torrent downloads
      downloadClientId: 0
      enable: true
      fields:
        - name: definitionFile
          value: 1337x
        - name: baseUrl
          value: https://1337x.proxyninja.org/
        - name: baseSettings.queryLimit
        - name: baseSettings.grabLimit
        - name: baseSettings.limitsUnit
          value: 0
        - name: torrentBaseSettings.appMinimumSeeders
        - name: torrentBaseSettings.seedRatio
        - name: torrentBaseSettings.seedTime
        - name: torrentBaseSettings.packSeedTime
        - name: downloadlink
          value: 1
        - name: downloadlink2
          value: 0
        - name: sort
          value: 0
        - name: type
          value: 1
      implementation: Cardigann
      implementationName: Cardigann
      indexerUrls:
        - https://1337x.to/
        - https://1337x.st/
        - https://x1337x.ws/
        - https://x1337x.eu/
        - https://x1337x.se/
        - https://1337x.so/
        - https://1337x.unblockit.africa/
        - https://1337x.unblockninja.com/
        - https://1337x.ninjaproxy1.com/
        - https://1337x.proxyninja.org/
        - https://1337x.torrentbay.st/
      infoLink: https://wiki.servarr.com/prowlarr/supported-indexers#1337x
      language: en-US
      legacyUrls:
        - https://1337x.is/
        - https://1337x.gd/
        - https://1337x.nocensor.lol/
        - https://1337x.unblockit.ink/
        - https://1337x.nocensor.art/
        - https://1337x.unblockit.bio/
        - https://1337x.unblockit.boo/
        - https://1337x.mrunblock.guru/
        - https://1337x.mrunblock.life/
        - https://1337x.unblockit.click/
        - https://1337x.unblockit.asia/
        - https://1337x.unblockit.mov/
        - https://1337x.unblockit.rsvp/
        - https://1337x.unblockit.vegas/
        - https://1337x.unblockit.esq/
        - https://1337x.unblockit.zip/
        - https://1337x.unblockit.foo/
        - https://1337x.unblockit.ing/
        - https://1337x.mrunblock.bond/
        - https://1337x.unblockit.date/
        - https://1337x.unblockit.dad/
      name: 1337x
      priority: 25
      privacy: public
      protocol: torrent
      redirect: false
      sortName: 1337x
      supportsPagination: false
      supportsRedirect: false
      supportsRss: true
      supportsSearch: true
      tags:
        - 1

volumes:
  storageClass: *storageClassName
  downloads:
    name: &downloads-volume downloads-volume
    size: 1Gi
  media:
    name: &media-volume media-volume
    size: 2Gi
  torrentConfig:
    name: &torrentConfig torrent-config
    size: 250Mi

sonarr:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    sonarr-ing:
      enabled: true
      primary: true
      required: true
      expandObjectName: false
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: sonarr.media.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - sonarr.media.local
          secretName: sonarr-tls
      integrations:
        certManager:
          enabled: false
        traefik:
          enabled: false
  persistence:
    config:
      enabled: true
      type: pvc
      size: 500Mi
      accessModes: ReadWriteMany
      storageClass: *storageClassName
      targetSelector:
        main:
          main:
            mountPath: /config
        exportarr:
          exportarr:
            mountPath: /config
            readOnly: true
    media:
      enabled: true
      type: pvc
      existingClaim: *media-volume
      targetSelector:
        main:
          main:
            mountPath: /mnt/media
    downloads:
      enabled: true
      type: pvc
      existingClaim: *downloads-volume
      targetSelector:
        main:
          main:
            mountPath: /mnt/downloads

radarr:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    radarr-ing:
      enabled: true
      primary: true
      required: true
      expandObjectName: false
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: radarr.media.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - radarr.media.local
          secretName: radarr-tls
      integrations:
        certManager:
          enabled: false
        traefik:
          enabled: false
  persistence:
    config:
      enabled: true
      type: pvc
      size: 500Mi
      accessModes: ReadWriteMany
      storageClass: *storageClassName
      targetSelector:
        main:
          main:
            mountPath: /config
        exportarr:
          exportarr:
            mountPath: /config
            readOnly: true
    media:
      enabled: true
      type: pvc
      existingClaim: *media-volume
      targetSelector:
        main:
          main:
            mountPath: /mnt/media
    downloads:
      enabled: true
      type: pvc
      existingClaim: *downloads-volume
      targetSelector:
        main:
          main:
            mountPath: /mnt/downloads

jellyfin:
  metrics:
    main:
      enabled: *metricsEnabled
  fallbackDefaults:
    storageClass:
    probeType: http
    serviceProtocol: tcp
    serviceType: ClusterIP
    persistenceType: pvc
    pvcRetain: false
    pvcSize: 100Gi
    vctSize: 100Gi
    accessModes:
      - ReadWriteMany
    vctAccessModes:
      - ReadWriteMany
    probeTimeouts:
      liveness:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 1
      readiness:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 2
      startup:
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 60
        successThreshold: 1
    pgVersion: 16
  serviceProtocol: tcp
  # @ignore
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              JELLYFIN_PublishedServerUrl: "https://jellyfin.media.local:8443/"
  ingress:
    jellyfin-ing:
      enabled: true
      primary: true
      required: true
      expandObjectName: false
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: jellyfin.media.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyfin.media.local
          secretName: jellyfin-tls
      integrations:
        certManager:
          enabled: false
        traefik:
          enabled: false
  persistence:
    transcode:
      enabled: false
    config:
      enabled: true
      type: pvc
      size: 500Mi
      accessModes: ReadWriteMany
      storageClass: *storageClassName
      targetSelector:
        main:
          main:
            mountPath: /config
        exportarr:
          exportarr:
            mountPath: /config
            readOnly: true
    media:
      enabled: true
      type: pvc
      existingClaim: *media-volume
      targetSelector:
        main:
          main:
            mountPath: /mnt/media

jellyseerr:
  metrics:
    main:
      enabled: *metricsEnabled
  fallbackDefaults:
    storageClass:
    probeType: http
    serviceProtocol: tcp
    serviceType: ClusterIP
    persistenceType: pvc
    pvcRetain: false
    pvcSize: 100Gi
    vctSize: 100Gi
    accessModes:
      - ReadWriteMany
    vctAccessModes:
      - ReadWriteMany
    probeTimeouts:
      liveness:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 1
      readiness:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 2
      startup:
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 60
        successThreshold: 1
    pgVersion: 16
  ingress:
    jellyseerr-ing:
      enabled: true
      primary: true
      required: true
      expandObjectName: false
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: jellyseerr.media.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyseerr.media.local
          secretName: jellyseerr-tls
      integrations:
        certManager:
          enabled: false
        traefik:
          enabled: false
  persistence:
    config:
      enabled: true
      type: pvc
      size: 500Mi
      accessModes: ReadWriteMany
      storageClass: *storageClassName
      targetSelector:
        main:
          main:
            mountPath: /app/config
        exportarr:
          exportarr:
            mountPath: /config
            readOnly: true
    media:
      enabled: true
      type: pvc
      existingClaim: *media-volume
      targetSelector:
        main:
          main:
            mountPath: /mnt/media

qbittorrent:
  csrf_protection: false
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              QBT_USE_PROFILE: true
  ingress:
    qbittorrent-ing:
      enabled: true
      primary: true
      required: true
      expandObjectName: false
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: torrent.media.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - torrent.media.local
          secretName: torrent-tls
      integrations:
        certManager:
          enabled: false
        traefik:
          enabled: false
  persistence:
    config:
      enabled: true
      type: pvc
      existingClaim: *torrentConfig
      targetSelector:
        main:
          main:
            mountPath: /config
        exportarr:
          exportarr:
            mountPath: /config
            readOnly: true
    downloads:
      enabled: true
      type: pvc
      existingClaim: *downloads-volume
      targetSelector:
        main:
          main:
            mountPath: /downloads

prowlarr:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    prowlarr-ing:
      enabled: true
      primary: true
      required: true
      expandObjectName: false
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: prowlarr.media.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - prowlarr.media.local
          secretName: prowlarr-tls
      integrations:
        certManager:
          enabled: false
        traefik:
          enabled: false
  persistence:
    config:
      enabled: true
      type: pvc
      size: 500Mi
      accessModes: ReadWriteMany
      storageClass: *storageClassName
      targetSelector:
        main:
          main:
            mountPath: /config
        exportarr:
          exportarr:
            mountPath: /config
            readOnly: true

flaresolverr:
  metrics:
    main:
      enabled: *metricsEnabled
  persistence:
    config:
      enabled: true
      type: pvc
      size: 500Mi
      accessModes: ReadWriteMany
      storageClass: *storageClassName
      targetSelector:
        main:
          main:
            mountPath: /config
        exportarr:
          exportarr:
            mountPath: /config
            readOnly: true
