helmDefaults:
  wait: true

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: jetstack
    url: https://charts.jetstack.io
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

releases:
  - name: cert-manager
    namespace: kube-system
    chart: jetstack/cert-manager
    version: v1.17.0
    values:
      - crds:
          enabled: true
        extraObjects:
          - |
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: selfsigned-cluster-issuer
              annotations:
                helm.sh/hook: post-install
                helm.sh/hook-delete-policy: hook-failed
                helm.sh/hook-weight: "10"
            spec:
              selfSigned: {}

  - name: nfs-subdir-external-provisioner
    namespace: kube-system
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values:
      - storageClass:
          name: nfs
        nfs:
          server: '{{ env "NFS_SERVER" | default "https" }}'
          path: "/"
          mountOptions: ["vers=4"]

  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 7.8.27
    createNamespace: true
    values: []
