apiVersion: v2
name: servarr
description: Servarr complete Helm Chart for Kubernetes
type: application
version: 0.20.6
appVersion: 0.20.6
keywords:
  - servarr
  - prowlarr
  - radarr
  - sonarr
  - qbittorrent
  - jellyseerr
  - jellyfin
  - flaresolverr
home: https://github.com/datahub-local/servarr
sources:
  - https://github.com/datahub-local/servarr
dependencies:
  - name: sonarr
    version: "25.2.6"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: sonarr.enabled
    tags:
      - tvseries
  - name: radarr
    version: "26.3.6"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: radarr.enabled
    tags:
      - movies
  - name: prowlarr
    version: "21.3.7"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: prowlarr.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: qbittorrent
    version: "24.2.7"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: qbittorrent.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: jellyseerr
    version: "13.13.7"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: jellyseerr.enabled
    tags:
      - movies
      - tvseries
  - name: jellyfin
    version: "22.2.11"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: jellyfin.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: flaresolverr
    version: "16.14.6"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: flaresolverr.enabled
    tags:
      - movies
      - tvseries
      - music
annotations:
  artifacthub.io/alternativeName: servar
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: AGPL-3.0-or-later
  artifacthub.io/prerelease: "false"
  artifacthub.io/maintainers: |
    - name: alvsanand
      email: alvsanand@gmail.com

maintainers:
  - name: alvsanand
    email: alvsanand@gmail.com
