apiVersion: v2
name: servarr
description: Servarr complete Helm Chart for Kubernetes
type: application
version: 0.23.0
appVersion: 0.23.0
keywords:
  - servarr
  - prowlarr
  - radarr
  - sonarr
  - qbittorrent
  - jellyseerr
  - jellyfin
  - flaresolverr
  - bazarr
  - audiobookshelf
  - auralarchive
home: https://github.com/datahub-local/servarr
sources:
  - https://github.com/datahub-local/servarr
annotations:
  artifacthub.io/alternativeName: servar
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: AGPL-3.0-or-later
  artifacthub.io/prerelease: "false"
  artifacthub.io/maintainers: |
    - name: alvsanand
      email: alvsanand@gmail.com
maintainers:
  - name: alvsanand
    email: alvsanand@gmail.com
dependencies:
  - name: sonarr
    version: "25.2.20"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: sonarr.enabled
    tags:
      - tvseries
  - name: radarr
    version: "26.3.20"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: radarr.enabled
    tags:
      - movies
  - name: prowlarr
    version: "21.3.21"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: prowlarr.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: qbittorrent
    version: "24.2.23"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: qbittorrent.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: jellyseerr
    version: "13.13.23"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: jellyseerr.enabled
    tags:
      - movies
      - tvseries
  - name: jellyfin
    version: "22.2.33"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: jellyfin.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: flaresolverr
    version: "16.14.17"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: flaresolverr.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: bazarr
    version: "23.2.21"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: bazarr.enabled
    tags:
      - movies
      - tvseries
  - name: audiobookshelf
    version: "12.20.14"
    repository: "oci://oci.trueforge.org/truecharts"
    # condition: audiobookshelf.enabled
    tags:
      - audiobooks
  - name: auralarchive
    version: "0.1.0"
    repository: "file://charts/auralarchive"
    # condition: auralarchive.enabled
    tags:
      - audiobooks
