apiVersion: v2
name: servarr
description: Servarr complete Helm Chart for Kubernetes
type: application
version: 0.12.3
appVersion: 0.12.3
keywords:
  - servarr
  - prowlarr
  - radarr
  - sonarr
  - qbittorrent
  - jellyseerr
  - jellyfin
  - flaresolverr
home: https://github.com/datahub-local/servarr
sources:
  - https://github.com/datahub-local/servarr
dependencies:
  - name: sonarr
    version: "24.6.2"
    repository: "oci://tccr.io/truecharts"
    # condition: sonarr.enabled
    tags:
      - tvseries
  - name: radarr
    version: "25.0.0"
    repository: "oci://tccr.io/truecharts"
    # condition: radarr.enabled
    tags:
      - movies
  - name: prowlarr
    version: "20.6.2"
    repository: "oci://tccr.io/truecharts"
    # condition: prowlarr.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: qbittorrent
    version: "23.5.2"
    repository: "oci://tccr.io/truecharts"
    # condition: qbittorrent.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: jellyseerr
    version: "13.5.2"
    repository: "oci://tccr.io/truecharts"
    # condition: jellyseerr.enabled
    tags:
      - movies
      - tvseries
  - name: jellyfin
    version: "21.5.2"
    repository: "oci://tccr.io/truecharts"
    # condition: jellyfin.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: flaresolverr
    version: "16.6.2"
    repository: "oci://tccr.io/truecharts"
    # condition: flaresolverr.enabled
    tags:
      - movies
      - tvseries
      - music
annotations:
  artifacthub.io/alternativeName: servar
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: AGPL-3.0-or-later
  artifacthub.io/prerelease: "false"
  artifacthub.io/maintainers: |
    - name: alvsanand
      email: alvsanand@gmail.com

maintainers:
  - name: alvsanand
    email: alvsanand@gmail.com
