{{- $downloads_pvc_name := .Values.volumes.downloads.name }}
{{- $is_downloads_pvc_present := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace $downloads_pvc_name) }}
{{- if or .Values.argoCD (not $is_downloads_pvc_present) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $downloads_pvc_name }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
  annotations:
    {{- include "servarr.annotations" . | nindent 4 }}
    #{{- if not .Values.argoCD }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    #{{- if not .Values.debug }}
    helm.sh/hook-delete-policy: hook-failed
    #{{- end }}
    #{{- end }}

    #{{- if .Values.argoCD }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    #{{- end }}
spec:
  storageClassName: {{.Values.volumes.storageClass}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.volumes.downloads.size}}
{{- end }}
---
{{- $media_pvc_name := .Values.volumes.media.name }}
{{- $is_media_pvc_present := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace $media_pvc_name) }}
{{- if or .Values.argoCD (not $is_media_pvc_present) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $media_pvc_name }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
  annotations:
    {{- include "servarr.annotations" . | nindent 4 }}
    #{{- if not .Values.argoCD }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    #{{- if not .Values.debug }}
    helm.sh/hook-delete-policy: hook-failed
    #{{- end }}
    #{{- end }}

    #{{- if .Values.argoCD }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    #{{- end }}
spec:
  storageClassName: {{.Values.volumes.storageClass}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.volumes.media.size}}
{{- end }}
---
{{- $torrentconfig_pvc_name := .Values.volumes.torrentConfig.name }}
{{- $is_torrentconfig_pvc_present := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace $torrentconfig_pvc_name) }}
{{- if or .Values.argoCD (not $is_torrentconfig_pvc_present) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $torrentconfig_pvc_name }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
  annotations:
    {{- include "servarr.annotations" . | nindent 4 }}
    #{{- if not .Values.argoCD }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    #{{- if not .Values.debug }}
    helm.sh/hook-delete-policy: hook-failed
    #{{- end }}
    #{{- end }}

    #{{- if .Values.argoCD }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    #{{- end }}
spec:
  storageClassName: {{.Values.volumes.storageClass}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.volumes.torrentConfig.size}}
{{- end }}
---
{{- $initconfig_pvc_name := .Values.volumes.initConfig.name }}
{{- $is_initconfig_pvc_present := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace $initconfig_pvc_name) }}
{{- if or .Values.argoCD (not $is_initconfig_pvc_present) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $initconfig_pvc_name }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
  annotations:
    {{- include "servarr.annotations" . | nindent 4 }}
    #{{- if not .Values.argoCD }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    #{{- if not .Values.debug }}
    helm.sh/hook-delete-policy: hook-failed
    #{{- end }}
    #{{- end }}

    #{{- if .Values.argoCD }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    #{{- end }}
spec:
  storageClassName: {{.Values.volumes.storageClass}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.volumes.initConfig.size}}
{{- end }}
