---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servarr.fullname" . }}-servarr-api-key
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
  annotations:
    {{- include "servarr.annotations" . | nindent 4 }}
type: Opaque
stringData:
  apikey: {{ include "servarr.apiKey" .Values.global.apikey }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servarr.fullname" . }}-qbittorrent-creds
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
  annotations:
    {{- include "servarr.annotations" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.torrent.username }}
  password: {{ .Values.torrent.password }}
