name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        stale-issue-label: 'stale'
        close-issue-label: 'dead'
        stale-pr-label: 'stale'
        close-pr-label: 'dead'
        stale-issue-message: 'This issue has been marked as stale because it has been open for 30 days with no activity. This thread will be automatically closed in 7 days if no further activity occurs.'
        stale-pr-message: 'This pull request has been marked as stale because it has been open for 30 days with no activity. This thread will be automatically closed in 7 days if no further activity occurs.'
        close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
        close-pr-message: 'This pull request was closed because it has been stalled for 7 days with no activity.'
        exempt-issue-labels: 'keep open'
        exempt-pr-labels: 'keep open'
        days-before-stale: 30
        days-before-close: 7
